//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalQuiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Burger
    {
        public int BurgerId { get; set; }
        public string BurgerName { get; set; }
        public int BurgerPrice { get; set; }
        public string BurgerStatus { get; set; }
    }
}
