//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatihanQuiz1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsRaman
    {
        public int RamenID { get; set; }
        public string RamenName { get; set; }
        public int RamenPrice { get; set; }
        public int RamenTypeID { get; set; }
    
        public virtual MsRamenType MsRamenType { get; set; }
    }
}
